### ISSUE TITLE
suggestion: led indication of ap mode

### ISSUE THREAD

**Issue by medoh300** [GameOver94/open-AutopilotPanel#1]
as on the real thing , one could have a led indicating which AP mode is selected : 

<img width="650" alt="Screenshot 2021-04-06 at 13 05 11" src="https://user-images.githubusercontent.com/51129115/113701717-ceb4f480-96d8-11eb-9500-7f3c429359ec.png">

a video of the real thing in action:

https://www.youtube.com/watch?v=TLRn8gpOxv0

**Comment by GameOver94** [comment]
I think currently it won't be possible because it will get synchronized. To do this an application has to run on the PC and hook into the flight sim and send back state of autopilot.

Additionally this will almost double the pins needed. I'm currently designing a PCB and to fit a second MCP23017 the push buttons and LEDs have to be surface mount components.

In the future I'm planing a version 2 which communicates via SimConnect. There I might consider this again but this will take a while.

**Comment by medoh300** [comment]
would it be possible with mobiflight and logic for lights maybe ?

**Comment by GameOver94** [comment]
I'm not very familiar with mobiflight but I think it might be possible but as far as I can tell the mobiflight firmware doesn't support the MCP23017 so the firmware has to be modified.
